site_name: matrix-python-sdk
repo_url: https://github.com/agent-matrix/matrix-python-sdk
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
nav:
  - Home: index.md
  - Installation: install.md
  - Usage Examples: usage.md
  - API:
      - Overview: api.md
  - Bulk Registration: bulk.md
  - API Reference: reference.md
  - Configuration: config.md
  - Contributing: contributing.md